Employers Data

In [5]:
import numpy as np
import pandas as pd
import os

print(os.getcwd())

d:\Python\TRY

In [7]:
df = pd.read_csv('Employees_raw_Data.csv.csv')
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes
...,...,...,...,...,...,...,...,...
303,Employee_214,Sales,2022-07-28 02:14:51,72054.11,39.0,3.0,Pune,No
304,Employee_107,Engineering,2020-04-10 15:05:25,67432.77,46.0,4.0,Bangalore,Yes
305,Employee_128,Finance,2020-09-22 04:29:42,NaN,29.0,4.0,Bangalore,No
306,Employee_177,Marketing,2021-10-11 03:46:21,62165.32,51.0,4.0,Bangalore,NO
307,Employee_74,Finance,2019-07-27 00:52:59,62111.89,30.0,2.0,Bangalore,Yes

In [8]:
df.head(5)

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes

In [10]:
df.tail(5)

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
303,Employee_214,Sales,2022-07-28 02:14:51,72054.11,39.0,3.0,Pune,No
304,Employee_107,Engineering,2020-04-10 15:05:25,67432.77,46.0,4.0,Bangalore,Yes
305,Employee_128,Finance,2020-09-22 04:29:42,NaN,29.0,4.0,Bangalore,No
306,Employee_177,Marketing,2021-10-11 03:46:21,62165.32,51.0,4.0,Bangalore,NO
307,Employee_74,Finance,2019-07-27 00:52:59,62111.89,30.0,2.0,Bangalore,Yes

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   emp_name            308 non-null    str
 1   department          295 non-null    str
 2   join_date           308 non-null    str
 3   salary              290 non-null    float64
 4   age                 298 non-null    float64
 5   performance_rating  291 non-null    float64
 6   city                308 non-null    str
 7   remote_work         281 non-null    str
dtypes: float64(3), str(5)
memory usage: 19.4 KB

In [14]:
df.size

2464

In [17]:
df.shape

(308, 8)

In [19]:
df.ndim

2

In [21]:
df.describe

<bound method NDFrame.describe of          emp_name   department            join_date    salary   age  \
0      Employee_1  Engineering  2018-01-01 00:00:00  60820.29  51.0
1      Employee_2          NaN  2018-01-08 20:04:01  48271.19  30.0
2      Employee_3           HR  2018-01-16 16:08:02  98590.99  55.0
3      Employee_4    Marketing  2018-01-24 12:12:02  71410.54  56.0
4      Employee_5        Sales  2018-02-01 08:16:03  23547.43  43.0
..            ...          ...                  ...       ...   ...
303  Employee_214        Sales  2022-07-28 02:14:51  72054.11  39.0
304  Employee_107  Engineering  2020-04-10 15:05:25  67432.77  46.0
305  Employee_128      Finance  2020-09-22 04:29:42       NaN  29.0
306  Employee_177    Marketing  2021-10-11 03:46:21  62165.32  51.0
307   Employee_74      Finance  2019-07-27 00:52:59  62111.89  30.0

     performance_rating       city remote_work
0                   4.0       Pune          No
1                   3.0      Delhi          No
2                   2.0     Mumbai          No
3                   3.0     Mumbai          No
4                   4.0    Chennai         yes
..                  ...        ...         ...
303                 3.0       Pune          No
304                 4.0  Bangalore         Yes
305                 4.0  Bangalore          No
306                 4.0  Bangalore          NO
307                 2.0  Bangalore         Yes

[308 rows x 8 columns]>

In [24]:
print(df.columns)

Index(['emp_name', 'department', 'join_date', 'salary', 'age',
       'performance_rating', 'city', 'remote_work'],
      dtype='str')

In [26]:
df.dtypes

emp_name                  str
department                str
join_date                 str
salary                float64
age                   float64
performance_rating    float64
city                      str
remote_work               str
dtype: object

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   emp_name            308 non-null    str
 1   department          295 non-null    str
 2   join_date           308 non-null    str
 3   salary              290 non-null    float64
 4   age                 298 non-null    float64
 5   performance_rating  291 non-null    float64
 6   city                308 non-null    str
 7   remote_work         281 non-null    str
dtypes: float64(3), str(5)
memory usage: 19.4 KB

In [33]:
df.info

<bound method DataFrame.info of          emp_name   department            join_date    salary   age  \
0      Employee_1  Engineering  2018-01-01 00:00:00  60820.29  51.0
1      Employee_2          NaN  2018-01-08 20:04:01  48271.19  30.0
2      Employee_3           HR  2018-01-16 16:08:02  98590.99  55.0
3      Employee_4    Marketing  2018-01-24 12:12:02  71410.54  56.0
4      Employee_5        Sales  2018-02-01 08:16:03  23547.43  43.0
..            ...          ...                  ...       ...   ...
303  Employee_214        Sales  2022-07-28 02:14:51  72054.11  39.0
304  Employee_107  Engineering  2020-04-10 15:05:25  67432.77  46.0
305  Employee_128      Finance  2020-09-22 04:29:42       NaN  29.0
306  Employee_177    Marketing  2021-10-11 03:46:21  62165.32  51.0
307   Employee_74      Finance  2019-07-27 00:52:59  62111.89  30.0

     performance_rating       city remote_work
0                   4.0       Pune          No
1                   3.0      Delhi          No
2                   2.0     Mumbai          No
3                   3.0     Mumbai          No
4                   4.0    Chennai         yes
..                  ...        ...         ...
303                 3.0       Pune          No
304                 4.0  Bangalore         Yes
305                 4.0  Bangalore          No
306                 4.0  Bangalore          NO
307                 2.0  Bangalore         Yes

[308 rows x 8 columns]>

In [35]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes
...,...,...,...,...,...,...,...,...
303,Employee_214,Sales,2022-07-28 02:14:51,72054.11,39.0,3.0,Pune,No
304,Employee_107,Engineering,2020-04-10 15:05:25,67432.77,46.0,4.0,Bangalore,Yes
305,Employee_128,Finance,2020-09-22 04:29:42,NaN,29.0,4.0,Bangalore,No
306,Employee_177,Marketing,2021-10-11 03:46:21,62165.32,51.0,4.0,Bangalore,NO
307,Employee_74,Finance,2019-07-27 00:52:59,62111.89,30.0,2.0,Bangalore,Yes

In [37]:
df.describe()

              salary         age  performance_rating
count     290.000000  298.000000          291.000000
mean    59624.215000   41.600671            3.584192
std     17629.028021   10.800842            1.071073
min      1657.190000   22.000000            1.000000
25%     47116.487500   33.000000            3.000000
50%     59723.160000   42.000000            4.000000
75%     71327.545000   51.000000            4.000000
max    115419.850000   59.000000            5.000000

In [41]:
maxi = df['salary'].max()
print(maxi)

115419.85

In [45]:
average = df['salary'].mean()
print(average)

59624.215000000004

In [47]:
mini = df['salary'].min()
print(mini)

1657.19

In [48]:
avg_age = df['age'].mean()
print(avg_age)

41.600671140939596

In [50]:
perfomance_rating = df['performance_rating'].mean()
print(perfomance_rating)

3.584192439862543

In [52]:
unique_dept = df['department'].unique()
print(unique_dept)

<StringArray>
['Engineering',           nan,          'HR',   'Marketing',       'Sales',
     'Finance',   'MARKETING', 'ENGINEERING',       'SALES']
Length: 9, dtype: str

In [53]:
unique_city = df['city'].unique()
print(unique_city)

<StringArray>
['Pune', 'Delhi', 'Mumbai', 'Chennai', 'Bangalore']
Length: 5, dtype: str

In [54]:
unique_remotework = df['remote_work'].unique()
print(unique_remotework)

<StringArray>
['No', 'yes', 'NO', 'Yes', nan]
Length: 5, dtype: str

In [56]:
df.isna()

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
303,False,False,False,False,False,False,False,False
304,False,False,False,False,False,False,False,False
305,False,False,False,True,False,False,False,False
306,False,False,False,False,False,False,False,False
307,False,False,False,False,False,False,False,False

In [59]:
#Find missing values in every column
df.isna().sum()

emp_name               0
department            13
join_date              0
salary                18
age                   10
performance_rating    17
city                   0
remote_work           27
dtype: int64

In [61]:
#Which column has most missing values
df.isna().sum().idxmax()

'remote_work'

In [67]:
# How many rows contain at least one missing value?
result = df.isna().any(axis=1).sum()
print(int(result))

74

In [69]:
percentage = (df.isna().any(axis=1).sum() /len(df)) * 100
print(percentage)

24.025974025974026