Creating A dataFrame
Selecting and Indexing of Columns
Creating a new Column
Removing Columns
Selecting Rows
Selecting subsets of Rows and Columns
Conditional  Selection

In [1]:
import numpy as np 
import pandas as pd

In [ ]:
data = {
    'Name':['John' , 'Anna' ,'Peter' , 'Linda'],
    'Age': [28 , 34 , 29 , 42],
    'City': ['New York' , 'Paris' ,'Berlin','London'],
    'Salary':[65000 , 70000 , 62000 , 85000]
}

df = pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [15]:
data_list = [
    ['John' , 28 , 'New York' , 65000],
    [ 'Anna', 34 , 'Paris' , 70000],
    ['Peter' , 29 , 'Berlin',62000],
    ['Linda' , 42 , 'London' , 85000]
]

df_2 = pd.DataFrame(data_list , index = arr)
columns = ["Name" , "Age" , "City", "Salary"]
df_2 = pd.DataFrame(data_list , columns=columns)
print(df_2)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and Indexing of Columns

In [12]:
df_2[['Name' , 'City']]

       Name    City
0      John   Peter
1        28      29
2  New York  Berlin
3     65000   62000

Creating a New Column

In [16]:
df_2['Designation'] = ['SWE' , 'Data Analyst' ,'Web Developer', 'Cloud Enginerr']
df_2

    Name  Age      City  Salary     Designation
0   John   28  New York   65000             SWE
1   Anna   34     Paris   70000    Data Analyst
2  Peter   29    Berlin   62000   Web Developer
3  Linda   42    London   85000  Cloud Enginerr

Removing Columns

In [21]:
df_2.drop('Designation' , axis = 1 , inplace=True)

In [22]:
df_2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selecting Rows

In [24]:
df_2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [27]:
df_2.loc[[0 , 1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

Selecting Subsets of Rows and Columns

In [30]:
df_2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [31]:
df_2.loc[[2 ,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [33]:
df_2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [38]:
df_2[df_2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [42]:
df_2[(df_2['Age'] > 30) & (df_2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000