Try the numpy and pandas

In [2]:
import numpy as np
import pandas as pd

In [6]:
arr = np.arange(1 , 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [9]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]

In [10]:
arr_1d = np.array([1 ,4 ,8 , 9 , 10])
print(arr_1d)

[ 1  4  8  9 10]

In [11]:
arr_2d = np.array([[2 , 4 , 5] , [8 , 7, 6]])
print(arr_2d)

[[2 4 5]
 [8 7 6]]

List vs Numpy

In [12]:
py_list = [ 5 , 6, 7]
print("Pyhton List Multiply ", py_list * 2)

Pyhton List Multiply  [5, 6, 7, 5, 6, 7]

In [13]:
np_arr = np.array([ 6, 7 , 8])
print(np_arr * 2)

[12 14 16]

In [14]:
np_arr = np.arange(2 , 21 , 2)
print(np_arr)

[ 2  4  6  8 10 12 14 16 18 20]

In [15]:
np_arr = np.arange(10 , 51, 5)
print(np_arr)

[10 15 20 25 30 35 40 45 50]

In [16]:
arr = np.array([[10 , 20 , 30] , [40 , 50 , 60]])
print(arr.size)

6

In [17]:
arr = np.array([[10 , 20 , 30] , [40 , 50 , 60]])
print(arr.ndim)

2

In [18]:
arr = np.array([[10 , 20 , 30] , [40 , 50 , 60]])
print(arr.shape)

(2, 3)

In [19]:
arr = np.array([[1 , 2 , 3],[4 , 5, 6] ,[7 , 8 , 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [20]:
arr = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 , 90])
print(arr[0])

10

In [21]:
arr = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 , 90])
print(arr[-1])

90

In [22]:
arr = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 , 90])
print(arr[1 : 4])

[20 30 40]

In [23]:
arr = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 , 90])
print(arr[2:])

[30 40 50 60 70 80 90]

In [24]:
arr = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 , 90])
print(arr[::-1])

[90 80 70 60 50 40 30 20 10]

In [25]:
arr = np.array([10 , 20 , 30 ,40 ,50])
print(arr.sum())

150

In [26]:
arr = np.array([10 , 20 , 30 ,40 ,50])
print(arr.mean())

30.0

In [27]:
arr = np.array([10 , 20 , 30 ,40 ,50])
print(arr.max())

50

In [28]:
arr = np.array([10 , 20 , 30 ,40 ,50])
print(arr.min())

10

In [29]:
arr = np.array([10 , 20 , 30 ,40 ,50])
print(arr.std())

14.142135623730951

In [30]:
arr = np.array([10 , 20 , 30 ,40 ,50])
print(arr.argmax())

4

In [31]:
arr = np.array([10 , 20 , 30 ,40 ,50])
print(arr * 2)

[ 20  40  60  80 100]

In [32]:
arr = np.array([10 , 20 , 30 ,40 ,50])
print(arr + 10)

[20 30 40 50 60]

In [33]:
arr = np.array([10 , 20 , 30 ,40 ,50])
print(arr[arr > 25])

[30 40 50]

In [34]:
arr = np.array([
    [10 , 20 , 30],
    [40 , 50 , 60],
    [70 , 80 , 90]
    ])
print(arr[1])

[40 50 60]

In [35]:
arr = np.array([
    [10 , 20 , 30],
    [40 , 50 , 60],
    [70 , 80 , 90]
    ])
print(arr[2])

[70 80 90]

In [36]:

#The syntax for a 2D NumPy array is:
#arr[row_slice, column_slice]
arr = np.array([
    [10 , 20 , 30],
    [40 , 50 , 60],
    [70 , 80 , 90]
    ])
print(arr[0:2,1:])

[[20 30]
 [50 60]]

In [37]:
"""
For a 2D array:

axis=0 → work down the rows → gives column-wise result
axis=1 → work across the columns → gives row-wise result
"""
arr = np.array([
    [10 , 20 , 30],
    [40 , 50 , 60],
    [70 , 80 , 90]
    ])
print(arr.sum(axis = 1))

[ 60 150 240]

In [38]:
arr = np.array([
    [10 , 20 , 30],
    [40 , 50 , 60],
    [70 , 80 , 90]
    ])
print(arr.sum(axis = 0))

[120 150 180]

In [39]:
arr = np.array([
    [10 , 20 , 30],
    [40 , 50 , 60],
    [70 , 80 , 90]
    ])
print(arr.max(axis = 1))

[30 60 90]

In [40]:
arr = np.array([
    [10 , 20 , 30],
    [40 , 50 , 60],
    [70 , 80 , 90]
    ])
print(arr.mean(axis = 0))

[40. 50. 60.]

In [41]:
arr = np.arange(1 , 13)
print(arr.reshape(3 , 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [42]:
arr = np.array([
    [10 , 20 , 30],
    [40 , 50 , 60],
    [70 , 80 , 90]
    ])
print(arr.flatten())

[10 20 30 40 50 60 70 80 90]

In [43]:
marks = np.array([45, 67, 89, 32, 76, 91, 55, 38])
print(marks[marks > 60])

[67 89 76 91]

In [44]:
marks = np.array([45, 67, 89, 32, 76, 91, 55, 38])
print(marks[marks< 50])

[45 32 38]

In [45]:
marks = np.array([45, 67, 89, 32, 76, 91, 55, 38])
print(marks[(marks > 50) & (marks < 80) ])

[67 76 55]

In [46]:
marks = np.array([45, 67, 89, 32, 76, 91, 55, 38])
print(np.sum(marks > 60))

4

Pandas Revision

In [47]:
df = pd.Series([10 , 20 , 30, 40])
df

0    10
1    20
2    30
3    40
dtype: int64

In [49]:
data = {
    "Name":["Rahul","Aman","Priya","Neha"],
    "Age":[20, 21, 20, 21],
    "Marks":[85, 72, 91, 65]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72
2  Priya   20     91
3   Neha   21     65

In [52]:
# Display the top two rows 
df.head(2)

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72

In [53]:
df.tail(2)

    Name  Age  Marks
2  Priya   20     91
3   Neha   21     65

In [55]:
df.shape

(4, 3)

In [57]:
df.info

<bound method DataFrame.info of     Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72
2  Priya   20     91
3   Neha   21     65>

In [60]:
df.describe()

            Age      Marks
count   4.00000   4.000000
mean   20.50000  78.250000
std     0.57735  11.870833
min    20.00000  65.000000
25%    20.00000  70.250000
50%    20.50000  78.500000
75%    21.00000  86.500000
max    21.00000  91.000000

In [ ]:
# Select only the Name column
df['Name']

0    Rahul
1     Aman
2    Priya
3     Neha
Name: Name, dtype: str

In [64]:
#This describe the no of columns
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [68]:
# Select Name and Marks
df[['Name','Marks']]

    Name  Marks
0  Rahul     85
1   Aman     72
2  Priya     91
3   Neha     65

In [71]:
#Select the first three rows
df.head(3)

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72
2  Priya   20     91

In [74]:
#Select the student whose name is Priya
df[df['Name'] == 'Priya']

    Name  Age  Marks
2  Priya   20     91

In [ ]:
#Select students whose marks greater than 75
df[df['Marks'] > 75]

    Name  Age  Marks
0  Rahul   20     85
2  Priya   20     91

In [78]:
# Select Students whose age is 20
df[df['Age'] == 20]

    Name  Age  Marks
0  Rahul   20     85
2  Priya   20     91

In [81]:
# Select students whose marks are between 70 and 90
df[(df['Marks'] >= 70) & (df['Marks']<=90)]

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72

In [86]:
#Add a new column called Passed
df['Passed'] = ["Pass","Pass","Pass","Pass"]
df

    Name  Age  Marks Passed
0  Rahul   20     85   Pass
1   Aman   21     72   Pass
2  Priya   20     91   Pass
3   Neha   21     65   Pass

In [87]:
df

    Name  Age  Marks Passed
0  Rahul   20     85   Pass
1   Aman   21     72   Pass
2  Priya   20     91   Pass
3   Neha   21     65   Pass

In [92]:
# Add a new column called Grade
df["Grade"] = ["B","C","A","D"]
df

    Name  Age  Marks Passed Grade
0  Rahul   20     85   Pass     B
1   Aman   21     72   Pass     C
2  Priya   20     91   Pass     A
3   Neha   21     65   Pass     D

In [93]:
df

    Name  Age  Marks Passed Grade
0  Rahul   20     85   Pass     B
1   Aman   21     72   Pass     C
2  Priya   20     91   Pass     A
3   Neha   21     65   Pass     D

In [105]:
df['Marks'] = df['Marks']+5
df

    Name  Age  Marks Passed Grade
0  Rahul   20     95   Pass     B
1   Aman   21     82   Pass     C
2  Priya   20    101   Pass     A
3   Neha   21     75   Pass     D

In [106]:
df

    Name  Age  Marks Passed Grade
0  Rahul   20     95   Pass     B
1   Aman   21     82   Pass     C
2  Priya   20    101   Pass     A
3   Neha   21     75   Pass     D

In [ ]:
#Change Neha's marks to 75.
df.loc[df['Name'] == 'Neha','Marks'] = 75
print(df)

    Name  Age  Marks Passed Grade
0  Rahul   20     95   Pass     B
1   Aman   21     82   Pass     C
2  Priya   20    101   Pass     A
3   Neha   21     75   Pass     D

In [ ]:
# Add a new student
df.loc[len(df)] = ['Karan' , 21 , 88 ,"Pass",'B']
print(df)

    Name  Age  Marks Passed Grade
0  Rahul   20     95   Pass     B
1   Aman   21     82   Pass     C
2  Priya   20    101   Pass     A
3   Neha   21     75   Pass     D
4  Karan   21     88   Pass     B
5  Karan   21     88   Pass     B

In [115]:
df.loc[df['Name'] == 'Karan'] = np.nan

In [ ]:
# df.drop(df[df['Name'] == ].index, inplace=True)
# df

    Name   Age  Marks Passed Grade
0  Rahul  20.0   95.0   Pass     B
1   Aman  21.0   82.0   Pass     C
2  Priya  20.0  101.0   Pass     A
3   Neha  21.0   75.0   Pass     D
4    NaN   NaN    NaN    NaN   NaN
5    NaN   NaN    NaN    NaN   NaN

In [ ]:
# Delete the row which contains NaN
df.dropna(how='all', inplace=True)

In [122]:
df

    Name   Age  Marks Passed Grade
0  Rahul  20.0   95.0   Pass     B
1   Aman  21.0   82.0   Pass     C
2  Priya  20.0  101.0   Pass     A
3   Neha  21.0   75.0   Pass     D